### ISSUE TITLE
Komentarze we własnym serializerze

### ISSUE THREAD

**Issue by Memexurer** [OkaeriPoland/okaeri-configs#12]
komentarze nie dzialaja kiedy zarejestruje sie customowego object serializera

**Comment by rusekhdev** [comment]
+1 naprawcie to bo nie moge żyć

**Comment by Memexurer** [comment]
nie wazne, nie umiem tego uzywac

**Comment by PinkLolicorn** [comment]
Przykładowy kod? Adnotacja do komentarzy będzie działać automatycznie tylko w klasie rozszerzającej OkaeriConfig i/lub użytej w kontekście innego automatycznie obsługiwanego OkaeriConfig.

Jeśli została zastosowana na pola w ręcznie obsługiwanym typie, nie jest to poprawne zastosowanie. Chociaż faktycznie w serializacji można by rozważyć coś w stylu `addComment(key, text)`.

Do subconfigów i typów przechowywanych z założenia w konfiguracji, jest mocno zalecane ustanowienie takiej klasy, jako element konfiguracji, rozszerzeniem OkaeriConfig.

**Comment by Memexurer** [comment]
nie o to mi chodzilo:
![image](https://user-images.githubusercontent.com/34003944/126228077-d47cbb19-608d-4271-8a7b-93ed9b2dccc9.png)
![image](https://user-images.githubusercontent.com/34003944/126228117-34730456-1aac-4f16-b373-cf31e6621257.png)

po prostu adnotacje nie dzialaja tak jak powinny

**Comment by PinkLolicorn** [comment]
Nie możesz korzystać z kropek w kluczu. To zależny od konkretnej implementacji (bukkita) sposób wyrażania sekcji i nie jest to wspierane przez bibliotekę w tej adnotacji. Powinieneś skorzystać z osadzonego configu, np. `DatabaseConfig`.

**Comment by Memexurer** [comment]
dzienki

**Comment by PinkLolicorn** [comment]
Jeszcze tak na podsumowanie dodam, że podczas, gdy niektóre backendy mogą obsługiwać kropki w kluczu, to ich używanie nie jest ogółem zalecane, bo bukkit interpretuje je jako sekcje. Zerknę potem na ewentualną możliwość dodania ostrzeżeń lub całkowitego traktowania kropki jako zwykły znak na tej platformie.

**Comment by Piechuuu** [comment]
unlucky
