### ISSUE TITLE
Issue apearing while trying to serialize, deserialize object which contains lists.

### ISSUE THREAD

**Issue by shitzuu** [OkaeriPoland/okaeri-configs#14]
This issue is appearing only in the latest version of **okaeri-configs** (3.0.0) in 2.7.24 this is working great.
**Stacktrace**: 
https://paste.gg/p/anonymous/1acfaa8469e84d388a1be7488fb8351b

**Comment by PinkLolicorn** [comment]
New safety check was incorrect due to a one letter typo. Fixed in https://github.com/OkaeriPoland/okaeri-configs/commit/5a4935494869799e72df9c87a84b01bf0b852755
