### ISSUE TITLE
Object with extends Okaeri Configs on map doesn't haas comments.

### ISSUE THREAD

**Issue by arturekdev** [OkaeriPoland/okaeri-configs#17]
**Describe the bug**
Object with extends Okaeri Configs on map doesn't haas comments.

**Library version**
3.1.0

**Config classes and setup routine**
![obraz](https://user-images.githubusercontent.com/61193738/128826724-5a8f776f-ffcb-486d-bdf4-74c0956945de.png)
![obraz](https://user-images.githubusercontent.com/61193738/128826755-2bbb22f7-def7-46c2-a47e-9aa7a7c35915.png)
![obraz](https://user-images.githubusercontent.com/61193738/128827006-2394f629-ffe3-4c7f-9cde-ab9a4844c1c0.png)

**Comment by PinkLolicorn** [comment]
This is a limitation of bukkit's YAML implementation, which does not provide any sensible way of implementing comments. The current implementation uses a simplified parser to apply some of these, capability extending PRs are welcome. The limitation is already described in the module's README: https://github.com/OkaeriPoland/okaeri-configs/tree/master/yaml-bukkit#limitations
