### ISSUE TITLE
[Feature Request] Adding missing keys on OkaeriConfigInitializer#saveDefaults

### ISSUE THREAD

**Issue by CDFN** [OkaeriPoland/okaeri-configs#6]
It'd be great if missing keys were added on `OkaeriConfigInitializer#saveDefaults`. Currently if we add field to a class and config file the class is assigned to already exists, new field isn't getting inserted into the config file.

**Comment by PinkLolicorn** [comment]
saveDefaults is used to save config only when the bindFile does not exist. To update comments/add new keys use save(true) where boolean means: "should we force update config?"
