### ISSUE TITLE
Problem z wygenerowaniem pliku yml

### ISSUE THREAD

**Issue by nejmik242** [OkaeriPoland/okaeri-configs#7]
Kod: https://hastebin.com/tipimociho.java
Wygenerowany config: https://hastebin.com/yeyoxezica.yaml

Chodzi o to, że w configu który generuje plugin nie są po kolei zmienne tak jak w kodzie. Jak to naprawić?

**Comment by PinkLolicorn** [comment]
Wystarczy użyć wersji `2.7.18` lub nowszej.

https://github.com/OkaeriPoland/okaeri-configs/commit/10341f6753ada47beed076fcc94d66a779bab0de#diff-7427d65bf79bfdf2b97f05b5df771b15127e774309e520bf5c3ec9ff7f48bb46R39-R41
